sum1 : {{$sum1}} <br>
sum2 : {{$sum2}} <br>
count1 : {{$count1}} <br>
count2 : {{$count2}} <br>
min1 : {{$min1}} <br>
min2 : {{$min2}} <br>
max1 : {{$max1}} <br>
max2 : {{$max2}} <br>
avg1 : {{$avg1}} <br>
avg2 : {{$avg2}} <br>